# Generated by Django 3.2.4 on 2021-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('video_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('thumbnail_url', models.URLField()),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Video details',
            },
        ),
    ]
